### ISSUE TITLE
Krypton detected, applying compatibility INFO spam

### ISSUE THREAD

**Issue by SulpherStaer** [RelativityMC/RaknetFabric#2]
The player was able to log in and had no connectivity issues. The server however complained about said player by giving several `Server thread/WARN Mismatch in destroy block pos:` errors.

```
22.02 23:03:59 [Server] Netty Epoll Server IO #0/INFO [STDOUT]: Krypton detected, applying compatibility
22.02 23:03:59 [Server] User Authenticator #11/INFO UUID of player [USERNAME REDACTED] is [UUID REDACTED]
22.02 23:03:59 [Server] Netty Epoll Server IO #0/WARN An exception was thrown by net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon$$Lambda$6896/0x0000000801da3668.operationComplete()
22.02 23:03:59 [Server] INFO java.lang.IllegalArgumentException: Duplicate handler name: decompress
22.02 23:03:59 [Server] INFO at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:247) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at net.minecraft.class_2535.handler$bhn000$setCompressionThreshold(class_2535.java:2057) ~[server-intermediary.jar:?]
22.02 23:03:59 [Server] INFO at net.minecraft.class_2535.method_10760(class_2535.java) ~[server-intermediary.jar:?]
22.02 23:03:59 [Server] INFO at net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon.lambda$sendCompressionPacket$2(ServerLoginNetworkAddon.java:117) ~[fabric-networking-api-v1-1.0.19+d7c144a865-27ddd48d544c3695.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:717) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:272) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.epoll.AbstractEpollChannel.doWriteBytes(AbstractEpollChannel.java:364) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytes(AbstractEpollStreamChannel.java:260) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteSingle(AbstractEpollStreamChannel.java:471) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:429) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:949) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:557) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:913) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254) ~[netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at net.minecraft.class_2535.doSendPacket(class_2535.java:1605) ~[server-intermediary.jar:?]
22.02 23:03:59 [Server] INFO at net.minecraft.class_2535.md076ce5$lambda$sendImmediately$rewrite$0$0(class_2535.java:1582) ~[server-intermediary.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
22.02 23:03:59 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
22.02 23:04:00 [Connect] User [USERNAME REDACTED], IP [IP REDACTED]
22.02 23:04:00 [Server] Server thread/INFO [USERNAME REDACTED] joined the game
```

**Comment by KJP12** [comment]
Have you updated to the latest CI build?
There's a fix there for this exact issue.

**Comment by SulpherStaer** [comment]
When I updated to 1.4 this issue went away. (but was replaced by another)
